process_market_price:
  outputs:
    dev:
      dbname: "{{ env_var('DBT_DBNAME') }}"
      user: "{{ env_var('DBT_USER') }}"
      host: "{{ env_var('DBT_HOST') }}"
      pass: "{{ env_var('DBT_PASS') }}"
      port: "{{ env_var('DBT_PORT') | int }}"
      schema: fact
      threads: 1
      type: postgres
  target: dev